import fs from 'node:fs';
import { queuePath } from '../utils/paths.js';
import { listTasks } from './manager.js';
import type { TaskFile } from './parser.js';

/**
 * Get the next pending or assigned task for a specific agent.
 * Priority: assigned to this agent > unassigned pending
 */
export function getNextTask(root: string, agentName: string): TaskFile | null {
  const tasks = listTasks(root);

  // First: tasks explicitly assigned to this agent
  const assigned = tasks.find(
    t => t.frontmatter.assigned_to === agentName &&
      (t.frontmatter.status === 'assigned' || t.frontmatter.status === 'pending')
  );
  if (assigned) return assigned;

  // Second: unassigned pending tasks
  const pending = tasks.find(
    t => !t.frontmatter.assigned_to && t.frontmatter.status === 'pending'
  );
  return pending ?? null;
}

/**
 * Generate the _queue.md summary file.
 */
export function generateQueueFile(root: string): void {
  const tasks = listTasks(root);

  const byStatus = {
    pending: tasks.filter(t => t.frontmatter.status === 'pending'),
    assigned: tasks.filter(t => t.frontmatter.status === 'assigned'),
    in_progress: tasks.filter(t => t.frontmatter.status === 'in_progress'),
    done: tasks.filter(t => t.frontmatter.status === 'done'),
    failed: tasks.filter(t => t.frontmatter.status === 'failed'),
    needs_human: tasks.filter(t => t.frontmatter.status === 'needs_human'),
  };

  const lines = [
    '# Task Queue',
    '',
    `> Auto-generated by stajyer daemon. Do not edit.`,
    '',
    `**Summary:** ${tasks.length} total | ${byStatus.pending.length} pending | ${byStatus.in_progress.length} in progress | ${byStatus.done.length} done | ${byStatus.failed.length} failed`,
    '',
  ];

  const formatTask = (t: TaskFile) => {
    const agent = t.frontmatter.assigned_to ? ` → ${t.frontmatter.assigned_to}` : '';
    return `- [${t.frontmatter.id}] ${t.frontmatter.title}${agent}`;
  };

  if (byStatus.in_progress.length > 0) {
    lines.push('## In Progress', ...byStatus.in_progress.map(formatTask), '');
  }
  if (byStatus.pending.length > 0 || byStatus.assigned.length > 0) {
    lines.push('## Pending', ...[...byStatus.assigned, ...byStatus.pending].map(formatTask), '');
  }
  if (byStatus.done.length > 0) {
    lines.push('## Done', ...byStatus.done.map(formatTask), '');
  }
  if (byStatus.failed.length > 0) {
    lines.push('## Failed', ...byStatus.failed.map(formatTask), '');
  }
  if (byStatus.needs_human.length > 0) {
    lines.push('## Needs Human', ...byStatus.needs_human.map(formatTask), '');
  }

  fs.writeFileSync(queuePath(root), lines.join('\n'), 'utf-8');
}
