import { Command } from 'commander';
import fs from 'node:fs';
import path from 'node:path';
import chalk from 'chalk';
import { input, select, number } from '@inquirer/prompts';
import { stajyerDir, tasksDir, commsDir, agentsDir, rulesDir } from '../utils/paths.js';
import { defaultConfig, GLOBAL_RULES_TEMPLATE, AGENT_PROFILE_TEMPLATE } from '../config/defaults.js';
import { saveConfig } from '../config/loader.js';
import type { StajyerConfig, AgentConfig } from '../config/schema.js';

export function registerInitCommand(program: Command): void {
  program
    .command('init')
    .description('Create .stajyer/ directory structure')
    .option('--yes', 'Skip prompts, use defaults')
    .action(async (opts) => {
      const root = process.cwd();
      const sDir = stajyerDir(root);

      if (fs.existsSync(sDir)) {
        console.log(chalk.yellow('  .stajyer/ already exists. Use --force to reinitialize.'));
        return;
      }

      console.log('');
      console.log(chalk.bold('  Welcome to Stajyer — your AI intern coordinator.'));
      console.log('');

      let config: StajyerConfig;

      if (opts.yes) {
        config = defaultConfig(path.basename(root));
      } else {
        const projectName = await input({
          message: 'Project name:',
          default: path.basename(root),
        });

        const workerCount = await number({
          message: 'How many worker agents?',
          default: 2,
        }) ?? 2;

        const adapter = await select({
          message: 'Which AI agent?',
          choices: [
            { name: 'Claude Code', value: 'claude-code' as const },
            { name: 'Codex', value: 'codex' as const },
            { name: 'Custom', value: 'custom' as const },
          ],
          default: 'claude-code',
        });

        config = defaultConfig(projectName);

        // Configure lead
        config.agents.lead.adapter = adapter;

        // Remove default dev-1, add configured workers
        delete config.agents['dev-1'];
        for (let i = 1; i <= workerCount; i++) {
          const name = `dev-${i}`;
          config.agents[name] = {
            adapter,
            config: { model: 'claude-sonnet-4-6', max_turns: 30 },
            role: `You are developer ${i}. You write code, fix bugs, and write tests.`,
            owns: ['src/**'],
          } satisfies AgentConfig;
        }
      }

      // Create directory tree
      const dirs = [
        sDir,
        tasksDir(root),
        commsDir(root),
        agentsDir(root),
        rulesDir(root),
      ];

      for (const dir of dirs) {
        fs.mkdirSync(dir, { recursive: true });
      }

      // Write config
      saveConfig(root, config);

      // Write global rules
      fs.writeFileSync(path.join(rulesDir(root), 'global.md'), GLOBAL_RULES_TEMPLATE, 'utf-8');

      // Write agent profiles
      for (const [name, agent] of Object.entries(config.agents)) {
        const profile = AGENT_PROFILE_TEMPLATE(name, agent.role ?? name);
        fs.writeFileSync(path.join(agentsDir(root), `${name}.md`), profile, 'utf-8');
      }

      // Write comms template
      fs.writeFileSync(
        path.join(commsDir(root), 'general.md'),
        '# General Communication\n\nAgents can write messages here for cross-team communication.\n',
        'utf-8'
      );

      // Write empty queue
      fs.writeFileSync(
        path.join(tasksDir(root), '_queue.md'),
        '# Task Queue\n\n> Auto-generated by stajyer daemon. Do not edit.\n\n**Summary:** 0 total\n',
        'utf-8'
      );

      console.log(chalk.green('  Created .stajyer/config.yml'));
      console.log(chalk.green('  Created .stajyer/tasks/'));
      console.log(chalk.green('  Created .stajyer/comms/'));
      console.log(chalk.green(`  Created .stajyer/agents/ (${Object.keys(config.agents).join(', ')})`));
      console.log(chalk.green('  Created .stajyer/rules/ (global.md)'));
      console.log('');
      console.log(chalk.bold('  Next steps:'));
      console.log('    1. Review .stajyer/config.yml');
      console.log('    2. Run: stajyer up');
      console.log('    3. Create your first task: stajyer task "Build the login page"');
      console.log('');
      console.log(chalk.dim('  Or let the lead handle everything:'));
      console.log(chalk.dim('    stajyer up'));
      console.log(chalk.dim('    stajyer task "Audit codebase and create tasks" --to lead'));
      console.log('');
    });
}
